version: "3.8"

services:
  mysql-local:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - ${MYSQL_LOCAL_PORT}
    volumes:
      - "data_volume:/var/lib/mysql-local"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  mysql-test:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - ${MYSQL_TEST_PORT}
    volumes:
      - "data_volume:/var/lib/mysql-test"
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
  minio:
    image: minio/minio
    ports:
      - ${MINIO_PORT}
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --address ":9099" /data

volumes:
  data_volume:
