version: "3.8"

services:
  mysql-main:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3308:3306"
    volumes:
      - "data_volume:/var/lib/mysql-local"
    environment:
      MYSQL_ROOT_PASSWORD: ${MAIN_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MAIN_MYSQL_DATABASE}
  mysql-test:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    ports:
      - "3309:3306"
    volumes:
      - "data_volume:/var/lib/mysql-test"
    environment:
      MYSQL_ROOT_PASSWORD: ${TEST_MYSQL_PASSWORD}
      MYSQL_DATABASE: ${TEST_MYSQL_DATABASE}
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9099:9099"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server --address ":9099" --console-address ":9000" /data

volumes:
  data_volume:
