name: Spring Boot Gradle Test Workflow

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      target-env:
        required: true
        type: string
    secrets:
      TEST_MYSQL_DATABASE:
        required: true
      TEST_MYSQL_USERNAME:
        required: true
      TEST_MYSQL_PASSWORD:
        required: true
      TEST_MYSQL_URL:
        required: true
      MINIO_URL:
        required: true
      MINIO_BUCKET:
        required: true
      MINIO_USER:
        required: true
      MINIO_PASSWORD:
        required: true
      TOKEN_ISSUER:
        required: true
      TOKEN_SECRET:
        required: true
      TOKEN_EXPIRATION:
        required: true
      FORECAST_SERVICE_KEY:
        required: true
      FORECAST_URL:
        required: true

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure docker-compose.yml
        uses: microsoft/variable-substitution@v1
        with:
          files: ./docker-compose.yml
        env:
          services.mysql-main.environment.MYSQL_ROOT_PASSWORD: ${{secrets.MAIN_MYSQL_PASSWORD}}
          services.mysql-main.environment.MYSQL_DATABASE: ${{secrets.MAIN_MYSQL_DATABASE}}
          services.mysql-test.environment.MYSQL_ROOT_PASSWORD: ${{secrets.TEST_MYSQL_PASSWORD}}
          services.mysql-test.environment.MYSQL_DATABASE: ${{secrets.TEST_MYSQL_DATABASE}}
          services.minio.environment.MINIO_ROOT_USER: ${{secrets.MINIO_USER}}
          services.minio.environment.MINIO_ROOT_PASSWORD: ${{secrets.MINIO_PASSWORD}}

      - name: echo files
        run: echo ./docker-compose.yml | echo ./src/test/resources/application.yaml

      # Build and start container
      - name: Build and Start Container
        run: docker-compose up -d

      # java 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'liberica'

      # gradle 권한 추가
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 프로젝트 빌드
      - name: Build with Gradle
        run: echo ./src/test/resources/application.yaml | ./gradlew clean build

      # Jacoco 테스트 결과 추가
      - name: 📑 Jacoco 테스트 결과
        id: jacoco
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: ${{github.workspace}}/**/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{secrets.GITHUB_TOKEN}}
          min-coverage-overall: 70
          min-coverage-changed-files: 70
